- .gitignore
- src/main.c
> read line and tokenizer

- src/main.c
tested with multiple external commands 
commit 1 : external command
commit 2 : exit function fixed and made the code extensible for builtin commands
> PSH_EXEC_EXTERNAL commands

- src/main.c
changed while condition from 'TRUE'->'run' removed unused variables
> Handling exit better and freeing all allocated memory before exiting

- src/main.c
in-built shell command PSH_CD implemented
co-authored-by: adi <pro.aditya.r@gmail.com>
> kk: shell function PSH_CD

- src/main.c
Added inbuilt command pwd ( pwd, pwd -L, pwd -P)
Removed time.h header file
> Added inbuilt command pwd[-L|-P]

- Makefile
- src/main.c
The cd function works somewhat with symlinks will fix that in the next commit .
this commit has the required functions and varible for it to work as of now.
Any guidence is appreciated.
> Added function for cd to work with symlink(still in progress)

- src/builtin.c
- src/builtin.h
- src/helpers.c
- src/main.c
- src/psh.h
- Created EXPORT function
- Works for export __ , export -p, export -n
- Modified READ function to accept variable assignment
- Added 2 helper functions to help with sorting
- Code for function declaration in READ function and EXPORT  function is commented
> EXPORT Function

- history_file.txt
- src/builtin.c
- src/builtin.h
- src/helpers.c
- src/main.c
- src/psh.h
History command changed to fc with some history features from bash integrated into fc as new fc features
> fc command

- src/builtin.c
- src/builtin.h
- src/helpers.c
- src/main.c
- src/psh.h
- Fixed cd .. not moving to link parent dir
- removed un-necessary variables and functions
> CD fix and more

- src/builtin.c
- src/psh.h
Fixed history file path to work along with fc function without causing seg faults.
> fixed history file paths

- src/builtin.c
- src/helpers.c
- src/psh.h
fc -rln is working now. fc -r -l -n needs to be fixxed and fc displays error as shown on dash
> fc -rln working

- src/builtin.c
so env variable expansion is possible, but it works for both double and single quotes.
> changes to echo code block

- README.md
The README has been finally updated for week 2 progress
> Updated readme for week 2

- src/execute.c
Tokenizer recognizes quotes and tokenizes data accordingly
> Updated Tokenizer to recognize quotes

- Makefile
- src/builtin.c
- src/execute.c
- src/helpers.c
- src/main.c
- src/psh.h
There is some other error but memory leaks are fixed
> FIXED FREES(MOSTLY),PLEASE USE free_double_pointer IN FUTURE

- script.sh
- src/main.c
- src/psh.h
usage : 
```bash
./bin/psh script.sh
```
> Script mode

- script.sh
> minor tweak

- src/main.c
i accidently merged main to my prev branch so i lost a few changes to had to re-do certain stuff.
> accident fix

- .gitignore
- Makefile
- src/builtin.c
- src/builtin.h
- src/execute.c
- src/helpers.c
- src/main.c
- src/psh.h
its now split into smaller part for use seperately
> changed read func and added some more

- src/builtin.c
- src/builtin.h
- src/execute.c
- src/helpers.c
- src/main.c
- src/psh.h
> added read, up arrow

- src/builtin.c
- src/execute.c
- src/helpers.c
- src/main.c
- src/psh.h
Session file gets created for every session with a unique session ID which gets written to the memory history file along with the command entered by the user
> multiple sessions working

- Makefile
- src/builtin.c
- src/execute.c
- src/helpers.c
- src/main.c
- src/psh.h
```
- fixed exit
- all arrow keys 
- and frees
```
> Up arrow fix

- src/builtin.c
- src/builtin.h
- src/execute.c
- src/helpers.c
- src/main.c
- src/psh.h
Alias function works but exits out of psh loop when called
> Alias function (errors)

- src/builtin.c
- src/execute.c
- src/helpers.c
- src/psh.h
Fixed execution of aliased commands
> Fixed Alias bugs

- src/builtin.c
- src/helpers.c
> Fixed 3 seg faults
